#!/bin/sh
#
# build_rom.sh - build the emulator ROMs for one RomWBW release.
#
# Usage: tools/build_rom.sh <romwbw-version>
# Output: build/<iface>-romwbw-<ver>/<rom-id>-<iface>-<ver>.rom
#
# A ROM is 512KB: bank 0 is our HBIOS proxy, assembled here from
# src/emu_hbios.asm; banks 1-15 are lifted verbatim from an upstream stock ROM
# so the ROM-resident loader, OS images and ROM disk are the real ones.
#
# The RomWBW version is NOT written in the assembly.  It is generated into
# romwbw_ver.inc from versions/<ver>/version.json, so the HCB at 0x105 and the
# proxy ident block at 0xFE02 cannot drift from each other or from the catalog.
# Before this repo they were two hand-copied `db 035h` pairs kept in step by a
# separate verify script.

set -eu
. "$(dirname "$0")/common.sh"

VER="${1:?usage: build_rom.sh <romwbw-version>}"
[ -f "$ROOT/versions/$VER/version.json" ] || die "unknown RomWBW version: $VER"
need_tools "$UM80" "$UL80"

TAG="$(release_tag "$VER")"
OUT="$BUILD/$TAG"
WORK="$BUILD/.rom-$VER"
STOCKDIR="$ROMWBW_CACHE/$(vjson "$VER" upstream.unpacked_dir)"

MAJOR="$(vjson "$VER" hbios.major)"; MINOR="$(vjson "$VER" hbios.minor)"
UPDATE="$(vjson "$VER" hbios.update)"; PATCH="$(vjson "$VER" hbios.patch)"
VER_BYTE="$(vjson "$VER" hbios.ver_byte)"; UPD_BYTE="$(vjson "$VER" hbios.upd_byte)"

# The four bytes emu_init.cc's emu_validate_rom_hcb reads back out of a loaded
# ROM: marker 'W' 0xA8 then the two packed version bytes.
WANT_HCB="57a8$(printf '%x%x%x%x' "$MAJOR" "$MINOR" "$UPDATE" "$PATCH")"

mkdir -p "$OUT"
# Clear this builder's OWN output, and only its own: build_rom.sh and
# build_disks.sh share $OUT, so "rm -rf $OUT" here would delete the
# other one's work. Stale ROMs under a name no catalog mentions would
# otherwise be uploaded to a tag this repo declares immutable.
rm -f "$OUT"/*.rom
rm -rf "$WORK"; mkdir -p "$WORK"

# um80 resolves `include` relative to the working directory, so the source and
# the generated include are assembled together in one scratch directory.
cp "$ROOT/src/emu_hbios.asm" "$WORK/"
{
  echo "; GENERATED by tools/build_rom.sh from versions/$VER/version.json - do not edit."
  echo "; RomWBW v$VER.  RomWBW packs its version into two bytes: high nibble"
  echo "; major/update, low nibble minor/patch."
  printf 'RMV_VER\tequ\t0%sh\t; (%s<<4)|%s\n' "${VER_BYTE#0x}" "$MAJOR" "$MINOR"
  printf 'RMV_UPD\tequ\t0%sh\t; (%s<<4)|%s\n' "${UPD_BYTE#0x}" "$UPDATE" "$PATCH"
} > "$WORK/romwbw_ver.inc"

echo "Building RomWBW v$VER ROMs  (HCB will read $WANT_HCB)"

( cd "$WORK" && "$UM80" -g emu_hbios.asm >um80.log 2>&1 ) ||
    { sed 's/^/      /' "$WORK/um80.log" >&2; die "emu_hbios.asm does not assemble"; }
( cd "$WORK" && "$UL80" -o emu_hbios.bin -p 0000 emu_hbios.rel >>um80.log 2>&1 ) ||
    { sed 's/^/      /' "$WORK/um80.log" >&2; die "emu_hbios.asm does not link"; }

note "bank 0: $(filesize "$WORK/emu_hbios.bin") bytes of code"

# Pad bank 0 to a full 32KB bank.
dd if=/dev/zero bs=32768 count=1 of="$WORK/bank0.bin" 2>/dev/null
dd if="$WORK/emu_hbios.bin" of="$WORK/bank0.bin" conv=notrunc 2>/dev/null

ROMJSON="$ROOT/versions/$VER/roms.json"
built=0
for id in $(python3 -c 'import json,sys; print(" ".join(r["id"] for r in json.load(open(sys.argv[1]))["roms"]))' "$ROMJSON"); do

    stock_rel="$(python3 -c 'import json,sys; print(next(r["stock"] for r in json.load(open(sys.argv[1]))["roms"] if r["id"]==sys.argv[2]))' "$ROMJSON" "$id")"
    stock="$STOCKDIR/$stock_rel"
    [ -f "$stock" ] || die "stock ROM missing: $stock
       Run: tools/fetch_romwbw.sh $VER"

    # Banks 1-15 must come from the SAME release the HCB claims, or the guest
    # CBIOS prints 'HBIOS/CBIOS Version Mismatch'.  Check the stock ROM's own
    # HCB rather than trusting the directory it was unpacked into.  This is
    # exactly the check that a v3.6.0-dev snapshot would otherwise pass.
    stock_ver="$(od -An -tx1 -j 261 -N 2 "$stock" | tr -d ' \n')"
    want_ver="$(printf '%x%x%x%x' "$MAJOR" "$MINOR" "$UPDATE" "$PATCH")"
    [ "$stock_ver" = "$want_ver" ] || die "$stock_rel carries HCB version $stock_ver, expected $want_ver for v$VER.
       Re-run tools/fetch_romwbw.sh $VER."
    [ "$(filesize "$stock")" = "524288" ] || die "$stock_rel is not 512KB"

    rom="$OUT/$(asset_name "$id" .rom "$VER")"
    dd if=/dev/zero bs=524288 count=1 of="$rom" 2>/dev/null
    dd if="$WORK/bank0.bin" of="$rom" bs=32768 count=1 conv=notrunc 2>/dev/null
    dd if="$stock" of="$rom" bs=32768 skip=1 seek=1 count=15 conv=notrunc 2>/dev/null

    got_hcb="$(od -An -tx1 -j 259 -N 4 "$rom" | tr -d ' \n')"
    if [ "$got_hcb" != "$WANT_HCB" ]; then
        rm -f "$rom"
        die "$id: built ROM has HCB $got_hcb at 0x103, expected $WANT_HCB.
       Removed it rather than leave a ROM that loads and dies."
    fi
    note "$(printf '%-34s %s  HCB %s' "$(basename "$rom")" "$(sha256of "$rom" | cut -c1-16)" "$got_hcb")"
    built=$((built + 1))
done

[ "$built" -gt 0 ] || die "no ROMs built"
rm -rf "$WORK"
echo "PASS: $built ROM(s) for RomWBW v$VER in $OUT"
